### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by htanjo** [htanjo/kss-node-template#6]
Hi! I'll resume developing the template and this is my roadmap:

- [ ] Support [kss-node](https://github.com/kss-node/kss-node) v2.x
- [ ] Publish to package managers ([npm](https://www.npmjs.com/), [bower](http://bower.io/))
- [ ] Responsive design
- [ ] Permalink of each section
- [ ] Copy to clipboard (like [Bootstrap docs](http://getbootstrap.com/css/))
- [ ] More compatibility with user css
- [ ] Update document and demo

If you have any ideas, feel free to tell me. RP is also welcome!

**Comment by htanjo** [comment]
I drop some features from 1.0.0 for quick release.
